name: sax
services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - sax-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:/app/opentelemetry-javaagent.jar"
      - DB_HOST=${DB_HOST}
      - OTEL_JAVAAGENT_DEBUG=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - sax-net


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml
    ports:
      - "55679:55679"
    expose:
      - 55679
    networks:
      - sax-net

  tempo:
    image: grafana/tempo:3.0.2
    command: ["-target=all", "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - sax-net

  loki:
    image: grafana/loki:3.7.0
    command: "-target=all -config.expand-env=true"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - sax-net

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    networks:
      - sax-net

networks:
  sax-net:
    driver: bridge
